# Generated by Django 3.0.5 on 2020-04-09 11:28

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to=projects.models.upload_img),
        ),
    ]
